name: "MariaDB (With External Access)"
version: "2.7.2-custom"
slug: "mariadb-external"
description: "MariaDB database with external network access for testing"
url: "https://github.com/home-assistant/addons/tree/master/mariadb"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
ports:
  3306/tcp: 3306  # EXPOSE PORT TO HOST NETWORK
ports_description:
  3306/tcp: "MariaDB (External access enabled)"
options:
  databases:
    - wpn_radius
  logins:
    - username: wpn-user
      password: C1sco5150!
  rights:
    - username: wpn-user
      database: wpn_radius
  # Allow external connections
  network_mode: host  # Use host networking
schema:
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - username: str
      database: str
  network_mode: str?
